(function(){'use strict';
const KEY='gr_characters', EQUIP='gr_equipped';
const defaults={blue:{name:'AURORA',image:'assets/ships/blue.png'},purple:{name:'NOVA',image:'assets/ships/purple.png'}};
function readShips(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function getEquipped(){return localStorage.getItem(EQUIP)||'blue'}
function stat(ship,key,fallback){const v=Number(ship&&ship[key]);return Number.isFinite(v)?v:fallback}
function build(){const overlay=document.getElementById('overlay-shop');if(!overlay||overlay.dataset.shipyardBuilt==='1')return;overlay.dataset.shipyardBuilt='1';overlay.classList.add('shipyard-enhanced');
 const stage=document.createElement('section');stage.className='shipyard-stage';stage.innerHTML='<div class="shipyard-preview"><div class="shipyard-grid"></div><div class="shipyard-status">HANGAR ONLINE</div><div class="shipyard-scan-ring"></div><img class="shipyard-ship" alt="Equipped ship preview"></div><div class="shipyard-specs"><div class="shipyard-identity"><div><div class="shipyard-level">SHIP SYSTEM</div><h2 class="shipyard-name">AURORA</h2></div><div class="shipyard-level shipyard-level-value">LV 1</div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>HULL</span><span class="shipyard-health-value">100</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill health"></div></div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>SPEED</span><span class="shipyard-speed-value">100</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill speed"></div></div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>ARMOR</span><span class="shipyard-armor-value">0</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill armor"></div></div></div><div class="shipyard-equipment"><span class="shipyard-chip">◆ FLIGHT READY</span><span class="shipyard-chip">◆ MOBILE OPTIMIZED</span><span class="shipyard-chip">◆ SYSTEM STABLE</span></div><div class="shipyard-actions"><span class="shipyard-action-note">Select an upgrade below to improve your ship.</span></div></div>';
 const list=document.getElementById('shop-list');if(list)overlay.insertBefore(stage,list);refresh();
}
function refresh(){const overlay=document.getElementById('overlay-shop');if(!overlay||overlay.dataset.shipyardBuilt!=='1')return;const ships=readShips();let id=getEquipped();if(!defaults[id])id='blue';const s=ships[id]||{};const meta=defaults[id];const level=Math.max(1,stat(s,'level',1));const health=Math.max(1,stat(s,'healthLv',stat(s,'maxHearts',1))*20);const speed=Math.max(1,stat(s,'speedLv',1)*20+60);const armor=Math.max(0,stat(s,'armor',stat(s,'healthLv',1)*5));
 const img=overlay.querySelector('.shipyard-ship');if(img){img.classList.remove('ship-blue','ship-purple');img.classList.add(id==='purple'?'ship-purple':'ship-blue');if(img.getAttribute('src')!==meta.image){img.src=meta.image}img.alt=meta.name+' ship';img.style.opacity='1'}
 const name=overlay.querySelector('.shipyard-name');if(name)name.textContent=meta.name+(id==='purple'?' • ELITE':'');const lv=overlay.querySelector('.shipyard-level-value');if(lv)lv.textContent='LV '+level;const hv=overlay.querySelector('.shipyard-health-value');if(hv)hv.textContent=health;const sv=overlay.querySelector('.shipyard-speed-value');if(sv)sv.textContent=speed;const av=overlay.querySelector('.shipyard-armor-value');if(av)av.textContent=armor;
 const hf=overlay.querySelector('.health');const sf=overlay.querySelector('.speed');const af=overlay.querySelector('.armor');if(hf)hf.style.width=Math.min(100,health/2)+'%';if(sf)sf.style.width=Math.min(100,speed/2)+'%';if(af)af.style.width=Math.min(100,armor)+'%';overlay.classList.toggle('shipyard-purple-mode',id==='purple');
}
function watch(){const overlay=document.getElementById('overlay-shop');if(!overlay)return;const observer=new MutationObserver(function(){if(!overlay.classList.contains('hidden')){build();refresh()}});observer.observe(overlay,{attributes:true,attributeFilter:['class']});overlay.addEventListener('click',function(e){if(e.target.closest('.shop-item,.shop-row,button'))setTimeout(refresh,120)});window.addEventListener('storage',refresh);setInterval(function(){if(!overlay.classList.contains('hidden'))refresh()},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();