(function(){'use strict';
const KEY='gr_characters', EQUIP='gr_equipped';
const defaults={blue:{name:'AURORA',image:'assets/ships/blue.png'},purple:{name:'NOVA',image:'assets/ships/purple.png'}};
function readShips(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function getEquipped(){const id=localStorage.getItem(EQUIP)||'blue';return defaults[id]?id:'blue'}
function selectShip(id){if(!defaults[id])return;localStorage.setItem(EQUIP,id);refresh();document.dispatchEvent(new CustomEvent('shipyard:shipSelected',{detail:{id:id}}))}
function stat(ship,key,fallback){const v=Number(ship&&ship[key]);return Number.isFinite(v)?v:fallback}
function shipCard(id,ship){const m=defaults[id];const level=Math.max(1,stat(ship,'level',1));const health=Math.max(1,stat(ship,'healthLv',stat(ship,'maxHearts',1))*20);const speed=Math.max(1,stat(ship,'speedLv',1)*20+60);const armor=Math.max(0,stat(ship,'armor',stat(ship,'healthLv',1)*5));const equipped=getEquipped()===id;return '<button type="button" class="shipyard-roster-card '+(equipped?'is-equipped ':'')+(id==='purple'?'is-purple':'is-blue')+'" data-ship-id="'+id+'" aria-pressed="'+equipped+'"><div class="shipyard-roster-top"><span class="shipyard-roster-code">'+(id==='blue'?'01':'02')+'</span><span class="shipyard-roster-state">'+(equipped?'EQUIPPED':'SELECT')+'</span></div><div class="shipyard-roster-visual"><div class="shipyard-roster-ring"></div><img src="'+m.image+'" alt="'+m.name+' ship" class="shipyard-roster-ship"></div><div class="shipyard-roster-name">'+m.name+(id==='purple'?' • ELITE':'')+'</div><div class="shipyard-roster-level">SHIP LEVEL <b>LV '+level+'</b></div><div class="shipyard-roster-stats"><span>HULL <b>'+health+'</b></span><span>SPEED <b>'+speed+'</b></span><span>ARMOR <b>'+armor+'</b></span></div><span class="shipyard-select-hint">'+(equipped?'ACTIVE SHIP':'TAP TO EQUIP')+'</span></button>'}
function build(){const overlay=document.getElementById('overlay-shop');if(!overlay)return;if(overlay.dataset.shipyardBuilt==='1'){refresh();return}overlay.dataset.shipyardBuilt='1';overlay.classList.add('shipyard-enhanced');
 const stage=document.createElement('section');stage.className='shipyard-stage';stage.innerHTML='<div class="shipyard-preview"><div class="shipyard-grid"></div><div class="shipyard-status">HANGAR ONLINE</div><div class="shipyard-scan-ring"></div><img class="shipyard-ship" alt="Equipped ship preview"></div><div class="shipyard-specs"><div class="shipyard-identity"><div><div class="shipyard-level">ACTIVE SHIP SYSTEM</div><h2 class="shipyard-name">AURORA</h2></div><div class="shipyard-level shipyard-level-value">LV 1</div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>HULL</span><span class="shipyard-health-value">100</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill health"></div></div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>SPEED</span><span class="shipyard-speed-value">100</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill speed"></div></div></div><div class="shipyard-stat"><div class="shipyard-stat-head"><span>ARMOR</span><span class="shipyard-armor-value">0</span></div><div class="shipyard-stat-track"><div class="shipyard-stat-fill armor"></div></div></div><div class="shipyard-equipment"><span class="shipyard-chip">◆ FLIGHT READY</span><span class="shipyard-chip">◆ MOBILE OPTIMIZED</span><span class="shipyard-chip">◆ SYSTEM STABLE</span></div></div>';
 const list=document.getElementById('shop-list');if(list){let roster=document.getElementById('shipyard-roster');if(!roster){roster=document.createElement('div');roster.id='shipyard-roster';list.parentNode.insertBefore(roster,list)}stage.querySelector('.shipyard-specs').insertAdjacentHTML('beforeend','<div class="shipyard-roster-title">SELECT YOUR SHIP</div>');overlay.insertBefore(stage,list)}refresh();}
function refresh(){const overlay=document.getElementById('overlay-shop');if(!overlay||overlay.dataset.shipyardBuilt!=='1')return;const ships=readShips();const id=getEquipped();const s=ships[id]||{};const meta=defaults[id];const level=Math.max(1,stat(s,'level',1));const health=Math.max(1,stat(s,'healthLv',stat(s,'maxHearts',1))*20);const speed=Math.max(1,stat(s,'speedLv',1)*20+60);const armor=Math.max(0,stat(s,'armor',stat(s,'healthLv',1)*5));
 const img=overlay.querySelector('.shipyard-ship');if(img){img.src=meta.image;img.alt=meta.name+' ship';img.style.opacity='1';img.classList.toggle('ship-purple',id==='purple');}
 const name=overlay.querySelector('.shipyard-name');if(name)name.textContent=meta.name+(id==='purple'?' • ELITE':'');const lv=overlay.querySelector('.shipyard-level-value');if(lv)lv.textContent='LV '+level;const hv=overlay.querySelector('.shipyard-health-value');if(hv)hv.textContent=health;const sv=overlay.querySelector('.shipyard-speed-value');if(sv)sv.textContent=speed;const av=overlay.querySelector('.shipyard-armor-value');if(av)av.textContent=armor;
 const hf=overlay.querySelector('.health');const sf=overlay.querySelector('.speed');const af=overlay.querySelector('.armor');if(hf)hf.style.width=Math.min(100,health/2)+'%';if(sf)sf.style.width=Math.min(100,speed/2)+'%';if(af)af.style.width=Math.min(100,armor)+'%';overlay.classList.toggle('shipyard-purple-mode',id==='purple');
 let roster=document.getElementById('shipyard-roster');if(!roster){roster=document.createElement('div');roster.id='shipyard-roster';const list=document.getElementById('shop-list');if(list&&list.parentNode)list.parentNode.insertBefore(roster,list)}roster.innerHTML=Object.keys(defaults).map(k=>shipCard(k,ships[k]||{})).join('');}
function showUpgradeMessage(text){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=text;toast.classList.remove('hidden');toast.classList.add('show');clearTimeout(showUpgradeMessage._timer);showUpgradeMessage._timer=setTimeout(()=>{toast.classList.remove('show');toast.classList.add('hidden')},1500)}
function syncSafeUpgradeButtons(){const overlay=document.getElementById('overlay-shop');if(!overlay)return;overlay.querySelectorAll('.upgrade-btn').forEach(btn=>{const ability=btn.dataset.ability;if(ability!=='health'&&ability!=='speed')return;const ships=readShips();const ship=ships[btn.dataset.char]||{};const lv=Math.max(0,stat(ship,ability+'Lv',0));const level=Math.max(1,stat(ship,'level',1));const cost=Math.round(40*(lv+1)*(1+(level-1)*0.5));const maxed=lv>=10;btn.disabled=maxed;btn.dataset.upgradeCost=String(cost);btn.textContent=maxed?'MAX':'💎'+cost;});}
function handleSafeUpgradeClick(e){const btn=e.target.closest('#overlay-shop.shipyard-enhanced .upgrade-btn');if(!btn)return;const ability=btn.dataset.ability;if(ability!=='health'&&ability!=='speed')return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();if(typeof upgradeAbility!=='function'){showUpgradeMessage('Upgrade system is unavailable.');return}const ok=upgradeAbility(btn.dataset.char,ability);if(!ok){const cost=Number(btn.dataset.upgradeCost||0);showUpgradeMessage(cost?'Need 💎 '+cost+' Rupees':'Upgrade unavailable');syncSafeUpgradeButtons();return}if(typeof Sound!=='undefined'&&Sound&&typeof Sound.upgrade==='function')Sound.upgrade();if(typeof renderShop==='function')renderShop();refresh();syncSafeUpgradeButtons();}
function watch(){const overlay=document.getElementById('overlay-shop');if(!overlay)return;const observer=new MutationObserver(function(){if(!overlay.classList.contains('hidden')){build();refresh();syncSafeUpgradeButtons()}});observer.observe(overlay,{attributes:true,attributeFilter:['class']});overlay.addEventListener('click',function(e){const card=e.target.closest('.shipyard-roster-card');if(card){e.preventDefault();selectShip(card.dataset.shipId);return}setTimeout(()=>{refresh();syncSafeUpgradeButtons()},120)});overlay.addEventListener('click',handleSafeUpgradeClick,true);window.addEventListener('storage',function(e){if(e.key===EQUIP||e.key===KEY)refresh()});setInterval(function(){if(!overlay.classList.contains('hidden')){refresh();syncSafeUpgradeButtons()}},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();
